version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweasdzxc
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s # How often to check if the container is healthy
      timeout: 5s # The maximum time a single check can run
      retries: 5 # How many retries before considering the container unhealthy

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: test_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweasdzxc
      POSTGRES_DB: test_db
      MONGODB_URI: mongodb://mongo:27917
      MONGODB_DB: test_db
    volumes:
      - .:/app

volumes:
  postgres_data:
  mongo_data:
