name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort autoflake wemake-python-styleguide flake8 mypy

    - name: Run autoflake to remove unused imports/variables
      run: |
        autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .

    - name: Run isort to sort imports
      run: |
        isort .

    - name: Run black to format code
      run: |
        black .

    - name: Lint with wemake-python-styleguide
      run: |
        flake8 . --config=setup.cfg --exit-zero

    - name: Type check with mypy
      run: |
        mypy . --config-file setup.cfg

    - name: Commit changes if any
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Apply auto-fixes for linting issues" || echo "No changes to commit"

    - name: Upload HTML linting report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: flake8-report
        path: flake8-report/index.html
